In [2]:
import torch, torchvision
model = torchvision.models.resnet18(weights=None)

In [3]:
data = torch.rand(1,3,64,64)
labels = torch.rand(1,1000)

In [4]:
prediction = model(data)

In [5]:
loss = (prediction - labels).sum()
print(loss)
loss.backward()

tensor(-502.1449, grad_fn=<SumBackward0>)


In [7]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [8]:
optim.step()

# 以下是求導的小測試

In [9]:
x1 = torch.ones((2,2))
x1

tensor([[1., 1.],
        [1., 1.]])

In [10]:
x2 = torch.ones((2, 2), requires_grad=True)
x2


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [11]:
y2 = x2+1

In [12]:
y2.requires_grad

True

In [15]:
a = torch.tensor([2.], requires_grad=True)
b = torch.tensor([4.], requires_grad=True)
y = a**2 + 2*b**3

In [16]:
y.backward()

In [20]:
print(a.grad)
print(b.grad)

tensor([4.])
tensor([96.])
