In [ ]:
import torch

In [ ]:
x = torch.empty(5,3)
print(type(x))
print(x)

In [ ]:
tensor_ones = torch.ones(2,3)
print(tensor_ones)
tensor_zeros = torch.zeros(2,3)
print(tensor_zeros)

In [ ]:
print(tensor_zeros.dtype)
tensor_zeros_int = torch.zeros(2,3,dtype=torch.long)
print(tensor_zeros_int.dtype)

In [ ]:
x = torch.rand(5,3)
print(x)
y = torch.randn(5,3)
print(y)

In [8]:
x = torch.tensor([5.5, 3])
print(x)


tensor([5.5000, 3.0000])


In [9]:
x = torch.tensor([5.5,3], dtype=torch.double)
print(x.dtype)
x = x.new_ones(5,3)
print(x)
x = torch.randn_like(x,dtype=torch.float)

torch.float64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x_size = x.size()
print(x_size)
row, col = x_size
print(row,col)

torch.Size([5, 3])
5 3


In [11]:
torch.arange(1, 10, 1)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
y = torch.rand(5, 3)
z1 = x+y
print(z1)

tensor([[-0.5877,  0.8948,  1.3345],
        [ 0.4532,  1.0026, -1.6157],
        [ 0.1923, -0.1966,  0.7997],
        [-1.7453,  1.5798, -1.4306],
        [ 0.7954,  1.2480,  1.7010]])


In [13]:
z2 = torch.add(x, y)
print(z2)

tensor([[-0.5877,  0.8948,  1.3345],
        [ 0.4532,  1.0026, -1.6157],
        [ 0.1923, -0.1966,  0.7997],
        [-1.7453,  1.5798, -1.4306],
        [ 0.7954,  1.2480,  1.7010]])


In [14]:
z3 = torch.empty(5, 3)
torch.add(x, y, out=z3)
print(z3)

tensor([[-0.5877,  0.8948,  1.3345],
        [ 0.4532,  1.0026, -1.6157],
        [ 0.1923, -0.1966,  0.7997],
        [-1.7453,  1.5798, -1.4306],
        [ 0.7954,  1.2480,  1.7010]])


In [15]:
y.add_(x)
print(y)

tensor([[-0.5877,  0.8948,  1.3345],
        [ 0.4532,  1.0026, -1.6157],
        [ 0.1923, -0.1966,  0.7997],
        [-1.7453,  1.5798, -1.4306],
        [ 0.7954,  1.2480,  1.7010]])


In [16]:
a = torch.randn(2, 3)
print(a)
b = torch.randn(2, 3)
print(b)

c = torch.sub(a, b)
print(c)
d = torch.mul(a, b)
print(d)
e = torch.div(a, b)
print(e)


tensor([[ 0.9885,  1.7463,  2.1286],
        [-1.1637,  0.6068, -1.9346]])
tensor([[ 0.8273, -0.3069, -0.0676],
        [-0.1522, -0.2809, -1.0866]])
tensor([[ 0.1612,  2.0532,  2.1962],
        [-1.0114,  0.8877, -0.8480]])
tensor([[ 0.8178, -0.5360, -0.1438],
        [ 0.1771, -0.1705,  2.1021]])
tensor([[  1.1948,  -5.6893, -31.5031],
        [  7.6447,  -2.1604,   1.7804]])


In [17]:
a = torch.randn(2,3)
print(a)
b = torch.mul(a,10)
print(b)
c = torch.div(a,10)
print(c)


tensor([[-0.8232, -0.0778, -0.9092],
        [ 1.0921, -0.0154, -0.1581]])
tensor([[-8.2320, -0.7783, -9.0920],
        [10.9214, -0.1545, -1.5809]])
tensor([[-0.0823, -0.0078, -0.0909],
        [ 0.1092, -0.0015, -0.0158]])


In [18]:
a = torch.randn(2,3)
print(a)
b = torch.rand(3,2)
print(b)
c = torch.mm(a,b)
print(c)

tensor([[-0.1715, -1.2408, -1.0224],
        [ 0.0805, -1.2096, -1.7069]])
tensor([[0.1304, 0.7541],
        [0.3339, 0.9186],
        [0.2769, 0.3612]])
tensor([[-0.7198, -1.6384],
        [-0.8660, -1.6670]])


In [19]:
a=torch.randn(2,3)
print(a)
b=torch.abs(a)
print(b)

tensor([[ 1.3588, -2.4076,  1.4915],
        [-0.3568, -1.7946,  0.6233]])
tensor([[1.3588, 2.4076, 1.4915],
        [0.3568, 1.7946, 0.6233]])


In [20]:
a = torch.randn(2,3)
print(a)
b = torch.pow(a,2)
print(b)

tensor([[ 1.9136, -1.4961, -0.3690],
        [-1.1165, -0.6045, -2.2466]])
tensor([[3.6618, 2.2384, 0.1362],
        [1.2465, 0.3654, 5.0472]])


In [24]:
print(x[:,:])

tensor([[-0.6766,  0.0212,  0.4698],
        [ 0.1431,  0.3185, -1.9290],
        [-0.1790, -1.0207,  0.1910],
        [-2.5729,  1.4697, -1.9364],
        [ 0.7135,  1.1224,  1.0760]])


In [27]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x)
print(y)
print(z)
print(x.size(),y.size(),z.size())

tensor([[-0.3836,  0.0195, -0.9976, -0.5053],
        [ 0.0894,  1.9141, -0.5155, -0.7144],
        [ 1.3354, -0.8256,  1.4721,  0.1610],
        [-0.1071, -1.4175, -0.5509, -1.3197]])
tensor([-0.3836,  0.0195, -0.9976, -0.5053,  0.0894,  1.9141, -0.5155, -0.7144,
         1.3354, -0.8256,  1.4721,  0.1610, -0.1071, -1.4175, -0.5509, -1.3197])
tensor([[-0.3836,  0.0195, -0.9976, -0.5053,  0.0894,  1.9141, -0.5155, -0.7144],
        [ 1.3354, -0.8256,  1.4721,  0.1610, -0.1071, -1.4175, -0.5509, -1.3197]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [28]:
x = torch.randn(2, 3)
print(x)
x_cat_dim0 = torch.cat((x, x, x), dim=0)
x_cat_dim1 = torch.cat((x, x, x), dim=1)
print(x_cat_dim0)
print(x_cat_dim1)

tensor([[ 1.3559, -0.3447,  0.1681],
        [ 0.7768,  0.1659, -0.3428]])
tensor([[ 1.3559, -0.3447,  0.1681],
        [ 0.7768,  0.1659, -0.3428],
        [ 1.3559, -0.3447,  0.1681],
        [ 0.7768,  0.1659, -0.3428],
        [ 1.3559, -0.3447,  0.1681],
        [ 0.7768,  0.1659, -0.3428]])
tensor([[ 1.3559, -0.3447,  0.1681,  1.3559, -0.3447,  0.1681,  1.3559, -0.3447,
          0.1681],
        [ 0.7768,  0.1659, -0.3428,  0.7768,  0.1659, -0.3428,  0.7768,  0.1659,
         -0.3428]])


In [29]:
x = torch.randn(1)
print(x)
print(x.size())
print(x.item())
print(type(x.item()))

tensor([0.6526])
torch.Size([1])
0.6525796055793762
<class 'float'>


In [30]:
a = torch.randn(2,3)
print(a)
b = torch.clamp(a,-0.5,0.5)
print(b)

tensor([[ 1.8601,  0.1042,  0.3347],
        [ 1.5871,  1.3555, -0.4067]])
tensor([[ 0.5000,  0.1042,  0.3347],
        [ 0.5000,  0.5000, -0.4067]])


In [35]:
import numpy as np
a = torch.ones(5)
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [36]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [37]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [38]:
print(torch.cuda.is_available())

True


In [39]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu",torch.double))

tensor([1.6526], device='cuda:0')
tensor([1.6526], dtype=torch.float64)
